version: '3'

services:
  # Wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - '80:80'
    restart: always
    volumes: 
      - wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
volumes:
  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/efs/UAS